In [19]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import torch
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter()

class MyNeuralNet(nn.Module):
    def __init__(self, input_size, n_nodes, output_size):
        super(MyNeuralNet, self).__init__()
        self.operationOne = nn.Linear(input_size, n_nodes)
        self.operationTwo = nn.Linear(n_nodes, output_size)
    def forward(self, x):
        x = F.relu(self.operationOne(x))
        x = self.operationTwo(x)
        x = F.sigmoid(x)
        return x

In [3]:
my_network = MyNeuralNet(input_size = 3, n_nodes = 2, output_size = 1)

Understanding Tensors

In [7]:
x = torch.arange(-5, 5, 0.1)
x1 = x.view(-1, 1)
y = -5 * x + 0.1 
y1 = y* torch.randn(x.size())

print( x)
print(x1)
print(y)

tensor([-5.0000e+00, -4.9000e+00, -4.8000e+00, -4.7000e+00, -4.6000e+00,
        -4.5000e+00, -4.4000e+00, -4.3000e+00, -4.2000e+00, -4.1000e+00,
        -4.0000e+00, -3.9000e+00, -3.8000e+00, -3.7000e+00, -3.6000e+00,
        -3.5000e+00, -3.4000e+00, -3.3000e+00, -3.2000e+00, -3.1000e+00,
        -3.0000e+00, -2.9000e+00, -2.8000e+00, -2.7000e+00, -2.6000e+00,
        -2.5000e+00, -2.4000e+00, -2.3000e+00, -2.2000e+00, -2.1000e+00,
        -2.0000e+00, -1.9000e+00, -1.8000e+00, -1.7000e+00, -1.6000e+00,
        -1.5000e+00, -1.4000e+00, -1.3000e+00, -1.2000e+00, -1.1000e+00,
        -1.0000e+00, -9.0000e-01, -8.0000e-01, -7.0000e-01, -6.0000e-01,
        -5.0000e-01, -4.0000e-01, -3.0000e-01, -2.0000e-01, -1.0000e-01,
        -2.9802e-09,  1.0000e-01,  2.0000e-01,  3.0000e-01,  4.0000e-01,
         5.0000e-01,  6.0000e-01,  7.0000e-01,  8.0000e-01,  9.0000e-01,
         1.0000e+00,  1.1000e+00,  1.2000e+00,  1.3000e+00,  1.4000e+00,
         1.5000e+00,  1.6000e+00,  1.7000e+00,  1.8

In [20]:
writer.add_scalar("x/y", x, y)

AssertionError: scalar should be 0D

In [17]:
torch.randn(x.size())

tensor([ 1.0564,  0.9115,  0.3953, -1.1420, -0.6362,  0.0538, -0.6254, -0.5420,
         0.3533, -0.2004, -1.2982,  0.1754, -1.3318,  0.6317,  2.7839,  0.3484,
         0.1859,  0.6615, -0.1924, -2.4078,  0.4499, -0.4666, -0.0809, -0.1233,
        -0.8396,  1.0294, -0.0740,  2.0547,  0.1963, -1.2814,  0.0813, -1.3054,
        -1.0788, -0.4756,  0.0541, -0.4810, -0.2415,  0.7360,  1.5896, -0.2902,
        -2.4846,  1.0368,  0.4812,  0.6129,  0.6217, -1.2466,  1.7905, -1.0581,
        -0.4851,  0.2428, -0.4902,  0.2387,  0.5080,  0.2834, -0.1050, -0.8785,
         3.0955, -0.1950, -0.0593,  0.9982, -0.0629,  0.4223,  1.3652, -0.0768,
        -0.2569, -1.4057, -0.8076, -0.6247, -0.9136, -1.3368,  2.3734,  0.0637,
        -2.7124,  0.3056, -0.4983, -0.0493, -0.1138, -0.2634, -0.5495, -0.4333,
         0.7022, -0.7491,  1.4151, -0.7105,  1.0171, -0.1307,  1.0909,  0.6550,
        -0.2832,  0.2644,  0.7609, -1.3703,  1.0177,  0.5629,  0.3803,  0.9083,
        -1.1965, -1.3057, -2.0444, -0.31

In [24]:
for _ in x :
    #print(_)
    #print(-5 * _)
    #print(-5 * _ + 0.1)
    #print(-5 * _ + 0.1 * torch.randn(x.size()))    
    writer.add_scalar("x/y", _, -5 * _ + 0.1)
    #writer.add_scalar("x/y", _)


In [7]:
import torch
first_order_tensor = torch.tensor([1, 2, 3])
print(first_order_tensor)

tensor([1, 2, 3])


In [15]:
print(first_order_tensor[0])

tensor(1)


In [16]:
print(first_order_tensor[0:2])

tensor([1, 2])


In [17]:
print(first_order_tensor[1:])

tensor([2, 3])


In [18]:
second_order_tensor = torch.tensor([ [ 11, 22, 33 ],
 [ 21, 22, 23 ]
 ])
print(second_order_tensor)

tensor([[11, 22, 33],
        [21, 22, 23]])


In [20]:
print(second_order_tensor[0, 1])

tensor(22)


In [21]:
fourth_order_tensor = torch.tensor(
[
 [
 [
 [1111, 1112],
 [1121, 1122]
 ],
 [
 [1211, 1212],
 [1221, 1222]
 ]
 ],
 [
 [
 [2111, 2112],
 [2121, 2122]
 ],
 [
 [2211, 2212],
 [2221, 2222]
 ]
 ]
])


In [22]:
my_tensor = torch.tensor([1, 2, 3, 4, 5])
print(my_tensor.size())

torch.Size([5])


In [23]:
my_tensor = torch.tensor([[11, 12, 13], [21, 22, 23]])
print(my_tensor.size())

torch.Size([2, 3])


In [24]:
print(fourth_order_tensor.size())

torch.Size([2, 2, 2, 2])


In [25]:
random_tensor = torch.rand([4, 2])
print(random_tensor)

tensor([[0.8849, 0.2496],
        [0.0906, 0.8850],
        [0.3370, 0.4994],
        [0.2537, 0.1573]])


In [26]:
random_tensor.view([2, 4])

tensor([[0.8849, 0.2496, 0.0906, 0.8850],
        [0.3370, 0.4994, 0.2537, 0.1573]])

In [27]:
random_tensor = torch.rand([4, 2, 4])
random_tensor.view([2, 4, -1])

tensor([[[0.0420, 0.2747, 0.9238, 0.6606],
         [0.8135, 0.1987, 0.3658, 0.7605],
         [0.1217, 0.5256, 0.4733, 0.1900],
         [0.7616, 0.0601, 0.1716, 0.6475]],

        [[0.4079, 0.0604, 0.9344, 0.1486],
         [0.8861, 0.7199, 0.5216, 0.0384],
         [0.9297, 0.8486, 0.2294, 0.3931],
         [0.7904, 0.9229, 0.3076, 0.5926]]])

In [28]:
random_tensor.view([2, -1, 4])

tensor([[[0.0420, 0.2747, 0.9238, 0.6606],
         [0.8135, 0.1987, 0.3658, 0.7605],
         [0.1217, 0.5256, 0.4733, 0.1900],
         [0.7616, 0.0601, 0.1716, 0.6475]],

        [[0.4079, 0.0604, 0.9344, 0.1486],
         [0.8861, 0.7199, 0.5216, 0.0384],
         [0.9297, 0.8486, 0.2294, 0.3931],
         [0.7904, 0.9229, 0.3076, 0.5926]]])

In [29]:
x = torch.tensor([5, 3])
y = torch.tensor([3, 2])
torch.add(x, y)

tensor([8, 5])

In [30]:
torch.sub(x, y)

tensor([2, 1])

In [32]:
torch.mul(x, y)

tensor([15,  6])

In [34]:
x + y

tensor([8, 5])

In [35]:
torch.div(x, y)

tensor([1, 1])

In [36]:
x.dtype

torch.int64

In [37]:
y.dtype

torch.int64

In [38]:
x_float = torch.tensor([5, 3], dtype = torch.float32)
y_float = torch.tensor([3, 2], dtype = torch.float32)
print(x_float / y_float)

tensor([1.6667, 1.5000])


In [39]:
torch.FloatTensor([5, 3])

tensor([5., 3.])

In [40]:
x.type(torch.DoubleTensor)

tensor([5., 3.], dtype=torch.float64)

Importing our dataset as a PyTorch Tensor

In [5]:
import numpy as np
admit_data = np.genfromtxt('admit_status.csv', delimiter = ',', skip_header = 1)
print(admit_data)

[[  0.   380.     3.61   3.  ]
 [  1.   660.     3.67   3.  ]
 [  1.   800.     4.     1.  ]
 [  1.   640.     3.19   4.  ]
 [  0.   520.     2.93   4.  ]
 [  1.   760.     3.     2.  ]
 [  1.   560.     2.98   1.  ]
 [  0.   400.     3.08   2.  ]
 [  1.   540.     3.39   3.  ]]


In [12]:
admit_tensor = torch.from_numpy(admit_data)
print(admit_tensor)

tensor([[  0.0000, 380.0000,   3.6100,   3.0000],
        [  1.0000, 660.0000,   3.6700,   3.0000],
        [  1.0000, 800.0000,   4.0000,   1.0000],
        [  1.0000, 640.0000,   3.1900,   4.0000],
        [  0.0000, 520.0000,   2.9300,   4.0000],
        [  1.0000, 760.0000,   3.0000,   2.0000],
        [  1.0000, 560.0000,   2.9800,   1.0000],
        [  0.0000, 400.0000,   3.0800,   2.0000],
        [  1.0000, 540.0000,   3.3900,   3.0000]], dtype=torch.float64)


Training neural networks in PyTorch

In [13]:
x_train = admit_tensor[:300, 1:].float()
y_train = admit_tensor[:300, 0].float()
x_test = admit_tensor[300:, 1:].float()
y_test = admit_tensor[300:, 0].float()

In [16]:
criterion = nn.BCELoss()

In [17]:
optimizer = torch.optim.SGD(my_network.parameters(), lr=0.01)

In [18]:
for epoch in range(100):
    y_pred = my_network(x_train)
    loss_score = criterion(y_pred, y_train)
    print('epoch: ', epoch, 'loss: ', loss_score)
    
    optimizer.zero_grad()
    loss_score.backward()
    optimizer.step()

epoch:  0 loss:  tensor(0.8205, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  1 loss:  tensor(0.8196, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  2 loss:  tensor(0.8187, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  3 loss:  tensor(0.8179, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  4 loss:  tensor(0.8170, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  5 loss:  tensor(0.8161, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  6 loss:  tensor(0.8152, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  7 loss:  tensor(0.8143, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  8 loss:  tensor(0.8135, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  9 loss:  tensor(0.8126, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  10 loss:  tensor(0.8118, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  11 loss:  tensor(0.8109, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  12 loss:  tensor(0.8100, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  13 loss:  tensor(0.8092, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  14 loss: